import './globals.css'
import { Inter } from 'next/font/google'
import Login from '@/pages/login/page'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({}) {
  return (
    <html lang="en">
      <body className={`dark ${inter.className}`}>
        {/* Will put login page here */}
        <Login />
      </body>
    </html>
  )
}
